version: '3.7'

networks:
  nic-net:
    driver: overlay

services:
  service_1:
    build: 
      context: ./project/service_1
    image: service_1
    ports:
      - "5000:5000"
    
    restart: always
    networks:
      - nic-net
    
    deploy:
      replicas: 3

  service_2:
    build: 
      context: ./project/service_2
    image: service_2
    
    restart: always
    networks:
      - nic-net
    deploy:
      replicas: 3


  service_3:
    build: 
      context: ./project/service_3
    image: service_3
    
    restart: always
    networks:
      - nic-net
    deploy:
      replicas: 3
  

  service_4:
    build: 
      context: ./project/service_4
    image: service_4
    
    restart: always
    networks:
      - nic-net
    deploy:
      replicas: 3
  
    
  service_nginx:
    image: nginx
      # ports:
      #   - "80:80"
    networks:
      - nic-net
    depends_on:
        - service_1
        - service_2
        - service_3
        - service_4
    deploy:
        replicas: 3






#under images paste the volumes syntax:
# volumes:
    #   - ./service_1:/var/lib/docker

# volumes:
    #   - ./service_2:/var/lib/docker

# volumes:
    #   - ./service_3:/var/lib/docker

# volumes:
    #   - ./service_4:/var/lib/docker